name: Clang Static Analysis

on:
  workflow_dispatch:
  push:

jobs:
  clang-analyzer:
    name: Clang static analysis
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         with:
          submodules: recursive
       - run: |
          sudo apt-get update
          sudo apt-get install -y libtool libtool-bin libcurl4-openssl-dev libpcap-dev clang-tools
       - run: |
          ./bootstrap.sh
          scan-build ./configure --with-glib=no
          scan-build --status-bugs make
